---
- name: Enable Mailbox for all AD users
  ansible.windows.win_shell: |
    Add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn
    $users = Get-User -RecipientTypeDetails User -ResultSize Unlimited | Where-Object { $_.RecipientTypeDetails -ne 'MailboxUser' }
    $excludedUsers = @("administrator", "ansible", "goadmin")
    foreach ($user in $users) {
        if (-not $excludedUsers -contains $user.samAccountName ) {
          if (-not $user.samAccountName.EndsWith('$')) {
            Enable-Mailbox -Identity $user.SamAccountName
          }
        }
    }
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ ludus_exchange_domain_username }}"
    ansible_become_password: "{{ ludus_exchange_domain_password }}"

- name: Disable mailbox splash screen
  ansible.windows.win_shell: |
    Add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn
    $users = Get-Mailbox -ResultSize Unlimited
    foreach ($user in $users) {
        Set-MailboxRegionalConfiguration -Identity $user.Alias -Language en-US -TimeZone "Romance Standard Time"
    }
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: "{{ ludus_exchange_domain_username }}"
    ansible_become_password: "{{ ludus_exchange_domain_password }}"