  - vm_name: "{{ range_id }}-GOAD-WS01"
    hostname: "{{ range_id }}-WS01"
    template: win10-21h1-x64-enterprise
    vlan: 10
    ip_last_octet: 30
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true