- name: Install client
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $device,

          [String]
          $password
      )
      Import-Module $env:SMS_ADMIN_UI_PATH.Replace("\bin\i386","\bin\configurationmanager.psd1") -force
      $SiteCode = Get-PSDrive -PSProvider CMSITE
      Set-Location ($SiteCode.Name +":")

      $client_active = Get-CMDevice| Select-Object Name, ClientActiveStatus
      foreach($c in $client_active) {
          if (($c.name -eq $device) -and (-not $c.ClientActiveStatus)) {
            Install-CMClient -DeviceName $device -SiteCode $SiteCode.Name -AlwaysInstallClient $True -IncludeDomainController $true
          }
      }
    parameters:
      device: "{{item}}"
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{domain_username}}"
    ansible_become_password: "{{domain_password}}"
  loop: "{{clients}}"

  Get-CMDevice| Select-Object Name, ClientActiveStatus