- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'

- name: "Setup Prerequisites"
  hosts: dc
  roles:
    - { role: 'dhcp', tags: 'dhcp_install'}
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.domains[domain].domain_password}}"
    dc_name: "DC"
    dc_fqdn: "{{dc_name}}.{{domain}}"
    ip_from: "192.168.33.150"
    ip_to: "192.168.33.200"
    ip_mask: "255.255.255.0"
    lease_duration: "1.00:00:00"
    dns_ip: "192.168.33.10"
