---
# Prepare servers
- import_playbook: build.yml
# Add monitoring
- import_playbook: elk.yml
# --------------------------------------------------------------------
# VM ready - start insert specific scenario
# --------------------------------------------------------------------
# Turn server into DC and load active directory data (users/groups/ou)
- import_playbook: ad.yml
# --------------------------------------------------------------------
# specifics vulns linked to the scenario are here
- import_playbook: vulns.yml