---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"

- name: "Setup vulnerabilities dc01"
  hosts: dc01
  roles:
    - { role: 'ps', tags: 'asrep_roasting', ps_script: "{{script_path}}/asrep_roasting.ps1"}
    - { role: 'ps', tags: 'kerberoasting', ps_script: "{{script_path}}/kerberoasting.ps1"}
    - { role: 'ps', tags: 'unconstrained_delegation', ps_script: "{{script_path}}/unconstrained_delegation.ps1"}
    - { role: 'ps', tags: 'acl', ps_script: "{{script_path}}/acl.ps1"}
    - { role: 'ps', tags: 'ntlm_relay', ps_script: "{{script_path}}/ntlm_relay.ps1"}
    #- { role: 'ps', tags: 'gpo_abuse', ps_script: "{{script_path}}/gpo_abuse.ps1"}
  vars:
    script_path: "../ad/{{domain_name}}/scripts"

- name: "Setup vulnerabilities dc02"
  hosts: dc02
  roles:
  vars:
    script_path: "../ad/{{domain_name}}/scripts"

- name: "Setup vulnerabilities srv"
  hosts: srv01
  roles:
    - { role: "vulns/openshares", tags: 'openshares'}
    - { role: 'ps', tags: 'responder', ps_script: "{{script_path}}/responder.ps1"}
  vars:
    script_path: "../ad/{{domain_name}}/scripts"
