# script source : https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/main/sccm-ps/ConfigurationManager/Set-CMClientPushInstallation.md
- name: Create Configuration For client push
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $pushAccount
      )
      # Step 1 - Import the Configuration Manager module
      Import-Module $env:SMS_ADMIN_UI_PATH.Replace("\bin\i386","\bin\configurationmanager.psd1") -force
      $SiteCode = Get-PSDrive -PSProvider CMSITE
      Set-Location ($SiteCode.Name +":")

      $sc=$SiteCode.Name
      Set-CMClientPushInstallation `
      -SiteCode $sc `
      -EnableAutomaticClientPushInstallation $True `
      -EnableSystemTypeConfigurationManager $True `
      -EnableSystemTypeServer $True `
      -AllownNTLMFallback $True `
      -EnableSystemTypeWorkstation $True `
      -InstallClientToDomainController $false `
      -AddAccount $pushAccount `
      -InstallationProperty "SMSSITECODE="+$sc
    parameters:
      pushAccount: "{{push_account}}"
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{domain_username}}"
    ansible_become_password: "{{domain_password}}"
