# https://www.prajwaldesai.com/install-sccm-distribution-point-using-powershell-script/

- name: Create PXE config 
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $pass
      )
      Import-Module $env:SMS_ADMIN_UI_PATH.Replace("\bin\i386","\bin\configurationmanager.psd1") -force
      $SiteCode = Get-PSDrive -PSProvider CMSITE
      Set-Location ($SiteCode.Name +":")

      #Define PXE Password
      $PXEpass = convertto-securestring -string $pass -asplaintext -force
      # get distribution point
      $DP = Get-CMDistributionPoint -SiteCode $SiteCode.Name
      # Enable PXE with password
      Set-CMDistributionPoint -InputObject $DP -EnablePxe $True -PXEpassword $PXEpass -AllowPxeResponse $True -EnableUnknownComputerSupport $True 
      #Enable Multicast Feature
      Add-CMMulticastServicePoint -SiteSystemServerName $DP -SiteCode $SiteCode.Name
    parameters:
      pass: "{{pxe_pass}}"
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{domain_username}}"
    ansible_become_password: "{{domain_password}}"